/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package User;

import DB.database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author lenovo
 */
public class TransaksiF extends javax.swing.JFrame {
    private int idGame;
    private int idUser;
    private int id_mata_uang;
    private String namaGame;
    private String namaMataUang;
    private int jumlah;
    private int harga;
    
    /**
     * Creates new form TransaksiF
     */
    public TransaksiF(int id_mata_uang, int id_game, int id_user) {
        this.id_mata_uang = id_mata_uang;
        this.idGame = id_game;
        this.idUser = id_user;
        initComponents();
        DetailGame();
        DetailUang();
        loadData();
    }
private void loadData(){
    lblnamagame1.setText("Nama Game: " + namaGame);
    lblmatauang1.setText(namaMataUang);
    lbljumlah1.setText("Jumlah: " + jumlah);
    lblharga.setText("Harga: " + harga);
}
 private void DetailGame() {
        Connection con = database.getConnection();
        String query = "SELECT nama_game FROM nama_game WHERE id_game = ?";
        try (PreparedStatement pst = con.prepareStatement(query)) {
            pst.setInt(1, idGame);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                namaGame = rs.getString("nama_game");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil detail game!");
        }
    }
  private void DetailUang() {
        Connection con = database.getConnection();
        String query = "SELECT nama_mata_uang, jumlah, harga FROM mata_uang_game WHERE id_mata_uang = ?";
        try (PreparedStatement pst = con.prepareStatement(query)) {
            pst.setInt(1, id_mata_uang);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                namaMataUang = rs.getString("nama_mata_uang");
                jumlah = rs.getInt("jumlah");
                harga = rs.getInt("harga");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengambil detail game!");
        }
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblharga = new javax.swing.JLabel();
        lblnamagame1 = new javax.swing.JLabel();
        lblmatauang1 = new javax.swing.JLabel();
        lbljumlah1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/icons8-game-100.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 80));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DHK");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setText("TOPUP");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        lblharga.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblharga.setText("s");
        jPanel1.add(lblharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        lblnamagame1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblnamagame1.setText("s");
        jPanel1.add(lblnamagame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        lblmatauang1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblmatauang1.setText("s");
        jPanel1.add(lblmatauang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 130, 40));

        lbljumlah1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbljumlah1.setText("s");
        jPanel1.add(lbljumlah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        jButton1.setText("KONFIRMASI");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));

        jButton2.setText("Kembali");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    LocalDateTime now = LocalDateTime.now();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    String formattedDateTime = now.format(formatter);

    Connection con = database.getConnection();

    try {
        // Check user balance
        String balanceQuery = "SELECT saldo FROM akun WHERE id_user = ?";
        try (PreparedStatement pstBalance = con.prepareStatement(balanceQuery)) {
            pstBalance.setInt(1, idUser);
            ResultSet rs = pstBalance.executeQuery();
            if (rs.next()) {
                int saldo = rs.getInt("saldo");
                
                // Check if the balance is sufficient
                if (saldo >= harga) {
                    // Update user balance
                    String updateBalanceQuery = "UPDATE akun SET saldo = saldo - ? WHERE id_user = ?";
                    try (PreparedStatement pstUpdateBalance = con.prepareStatement(updateBalanceQuery)) {
                        pstUpdateBalance.setInt(1, harga);
                        pstUpdateBalance.setInt(2, idUser);
                        pstUpdateBalance.executeUpdate();
                    }

                    // Insert transaction record
                    String transactionQuery = "INSERT INTO transaksi (id_user, id_mata_uang, tanggal_transaksi, status) VALUES (?, ?, ?, 'Pending')";
                    try (PreparedStatement pstTransaction = con.prepareStatement(transactionQuery)) {
                        pstTransaction.setInt(1, idUser);
                        pstTransaction.setInt(2, id_mata_uang);
                        pstTransaction.setString(3, formattedDateTime);
                        pstTransaction.executeUpdate();
                        JOptionPane.showMessageDialog(this, "Pembelian berhasil dikonfirmasi!");
                        
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Saldo tidak cukup!");
                }
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengkonfirmasi pembelian!");
    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         User.Money obj = new User.Money(idGame, idUser); // Ganti id_user menjadi idUser
                    obj.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblharga;
    private javax.swing.JLabel lbljumlah1;
    private javax.swing.JLabel lblmatauang1;
    private javax.swing.JLabel lblnamagame1;
    // End of variables declaration//GEN-END:variables
}
